config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    @article.save

    redirect_to article_path(@article)
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    redirect_to article_path(@article)
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(article) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

<%= link_to "Back to list", articles_path %>

app/views/articles/index.html.erb
<div class="d-flex">
  <div class="container">
    <ul class="list-group">
      <% @articles.each do |article| %>
        <li class="list-group-item shadow p-3 mb-2 bg-body rounded">
          <h2><%= link_to article.title, article_path(article) %></h2>
          <p><%= article.content %></p>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<%= link_to "Delete #{@article.title}",
            article_path(@article),
            method: :delete,
            data: { confirm: "Are you sure?" } %>

<blockquote><%= @article.content %></blockquote>


<%= link_to "Edit this article", edit_article_path %>


<%= link_to "Back to list", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid shadow">
        <a class="navbar-brand" href="<%= articles_path %>">Wikinimous</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>